version: 2
jobs:
   build:
     docker:
      - image: buildpack-deps:trusty
     steps:
       - checkout
       - run: mkdir -p Build
       - run: |
            sudo apt-get update
            sudo apt-get install g++-4.9
       - run: |
            gcc --version
            g++ --version
            cmake --version
       - run: |
            cd ~/project/Build
            cmake -G "Unix Makefiles" ~/project/cmake -DPROJECT_SOURCE_DIR:PATH=~/project/cmake -DPROJECT_BINARY_DIR:PATH=~/project/Build
       - run: |
            cd ~/project/Build
            make -d