version: 2
jobs:
   build:
     machine: true
     steps:
       - checkout
       - run: echo "hello world"
       - run: mkdir -p Build
       - run: cd Build
       - run: ls /home/circleci/project/cmake/../experiment/test
       - run: cmake ~/project/cmake
       - run: make