version: 2
jobs:
   build:
     machine:
      - image: library/gcc:5.5.0
     steps:
       - checkout
       - run: mkdir -p Build
       - run: sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5.5.0 60 --slave /usr/bin/g++ g++ /usr/bin/g++-5.5.0
       - run: |
            gcc --version
            g++ --version
            cmake --version
       - run: |
            cd ~/project/Build
            cmake -G "Unix Makefiles" ~/project/cmake -DPROJECT_SOURCE_DIR:PATH=~/project/cmake -DPROJECT_BINARY_DIR:PATH=~/project/Build
       - run: |
            cd ~/project/Build
            make -d