version: 2
jobs:
   build:
     docker:
      - image: library/gcc:5.5.0
     steps:
       - checkout
       - run: sudo apt-get install cmake
       - run: mkdir -p Build
       - run: |
            gcc --version
            g++ --version
            cmake --version
       - run: |
            cd ~/project/Build
            cmake -G "Unix Makefiles" ~/project/cmake -DPROJECT_SOURCE_DIR:PATH=~/project/cmake -DPROJECT_BINARY_DIR:PATH=~/project/Build
       - run: |
            cd ~/project/Build
            make -d