version: 2
jobs:
   build:
     machine: true
     steps:
       - run: |
            sudo add-apt-repository ppa:ubuntu-toolchain-r/test 
            sudo apt-get update
            sudo apt-get install gcc-4.9
            sudo apt-get install g++-4.9
       - checkout
       - run: mkdir -p Build
       - run: |
            gcc --version
            g++ --version
       - run: |
            cd ~/project/Build
            cmake -G "Unix Makefiles" ~/project/cmake -DPROJECT_SOURCE_DIR:PATH=~/project/cmake -DPROJECT_BINARY_DIR:PATH=~/project/Build
       - run: |
            cd ~/project/Build
            make -d