version: 2
jobs:
   build:
     machine: true
     steps:
       - checkout
       - run: mkdir -p Build
       - run: cmake -G "Unix Makefiles" ~/project/cmake -DPROJECT_SOURCE_DIR:PATH=~/project/cmake -DPROJECT_BINARY_DIR:PATH=~/project/Build
       - run: make -d