version: 2
jobs:
   build:
     docker: 
       - image: library/gcc:5.5.0
     steps:
       - checkout
       - run: mkdir -p Build
       - run: |
            curl -sSL https://cmake.org/files/v3.9/cmake-3.9.6-Linux-x86_64.tar.gz | sudo tar -xzC /opt
       - run: |
            gcc --version
            g++ --version
            cmake --version
       - run: |
            cd ~/project/Build
            cmake -G "Unix Makefiles" ~/project/cmake -DPROJECT_SOURCE_DIR:PATH=~/project/cmake -DPROJECT_BINARY_DIR:PATH=~/project/Build
       - run: |
            cd ~/project/Build
            make