version: 2
jobs:
   build:
     docker: 
       - image: library/gcc:5.5.0
     steps:
       - checkout
       - run: mkdir -p Build
       - run: |
            cd ~
            wget https://cmake.org/files/v3.10/cmake-3.10.0.tar.gz
            tar xzf cmake-3.10.0.tar.gz
            cd cmake-3.10.0
            ./bootstrap
            make
            make install
       - run: |
            gcc --version
            g++ --version
            cmake --version
       - run: |
            cd ~/project/Build
            cmake -G "Unix Makefiles" ~/project/cmake -DPROJECT_SOURCE_DIR:PATH=~/project/cmake -DPROJECT_BINARY_DIR:PATH=~/project/Build
       - run: |
            cd ~/project/Build
            make -d