#ifndef TOOL_CHARACTER_VALUES_H_
#define TOOL_CHARACTER_VALUES_H_

namespace tool
{
	namespace character
	{
		typedef unsigned char ValuesIntegerType;
		enum Values : ValuesIntegerType;
	}
}

enum tool::character::Values :
	tool::character::ValuesIntegerType
{
	control_null = '\0',
	control_start_of_heading = '\1',
	control_start_of_text = '\2',
	control_end_of_text = '\3',
	control_end_of_transmission = '\4',
	control_enquiry_character = '\5',
	control_acknowledgement = '\6',
	control_bell = '\a',
	control_backspace = '\b',
	control_horizontal_tabulation = '\t',
	control_line_feed = '\n',
	control_vertical_tabulation = '\v',
	control_form_feed = '\f',
	control_carriage_return = '\r',
	control_shift_out = '\14',
	control_shift_in = '\15',
	control_data_link_escape = '\16',
	control_device_1 = '\17',
	control_device_2 = '\18',
	control_device_3 = '\19',
	control_device_4 = '\20',
	control_negative_acknowledgement = '\21',
	control_synchronous_idle = '\22',
	control_end_of_transmission_block = '\23',
	control_cancel = '\24',
	control_end_of_medium = '\25',
	control_substitute = '\26',
	control_escape = '\27',
	control_file_separator = '\28',
	control_group_separator = '\29',
	control_record_separator = '\30',
	control_unit_separator = '\31',
	punctuation_space = ' ',
	punctuation_exclamation_mark = '!',
	punctuation_quotation_mark = '\"',
	punctuation_number_sign = '#',
	punctuation_dollar_sign = '$',
	punctuation_percent_sign = '%',
	punctuation_ampersand = '&',
	punctuation_apostrophe = '\'',
	punctuation_left_parenthesis = '(',
	punctuation_right_parenthesis = ')',
	punctuation_asterisk = '*',
	punctuation_plus_sign = '+',
	punctuation_comma = ',',
	punctuation_hyphen_minus = '-',
	punctuation_full_stop = '.',
	punctuation_slash = '/',
	digit_0 = '0',
	digit_1 = '1',
	digit_2 = '2',
	digit_3 = '3',
	digit_4 = '4',
	digit_5 = '5',
	digit_6 = '6',
	digit_7 = '7',
	digit_8 = '8',
	digit_9 = '9',
	punctuation_colon = ':',
	punctuation_semicolon = ';',
	punctuation_less_than_sign = '<',
	punctuation_equals_sign = '=',
	punctuation_greater_than_sign = '>',
	punctuation_question_mark = '?',
	punctuation_at_sign = '@',
	alphabetic_upper_a = 'A',
	alphabetic_upper_b = 'B',
	alphabetic_upper_c = 'C',
	alphabetic_upper_d = 'D',
	alphabetic_upper_e = 'E',
	alphabetic_upper_f = 'F',
	alphabetic_upper_g = 'G',
	alphabetic_upper_h = 'H',
	alphabetic_upper_i = 'I',
	alphabetic_upper_j = 'J',
	alphabetic_upper_k = 'K',
	alphabetic_upper_l = 'L',
	alphabetic_upper_m = 'M',
	alphabetic_upper_n = 'N',
	alphabetic_upper_o = 'O',
	alphabetic_upper_p = 'P',
	alphabetic_upper_q = 'Q',
	alphabetic_upper_r = 'R',
	alphabetic_upper_s = 'S',
	alphabetic_upper_t = 'T',
	alphabetic_upper_u = 'U',
	alphabetic_upper_v = 'V',
	alphabetic_upper_w = 'W',
	alphabetic_upper_x = 'X',
	alphabetic_upper_y = 'Y',
	alphabetic_upper_z = 'Z',
	punctuation_left_square_bracket = '[',
	punctuation_backslash = '\\',
	punctuation_right_square_bracket = ']',
	punctuation_caret = '^',
	punctuation_underscore = '_',
	punctuation_grave_accent = '`',
	alphabetic_lower_a = 'a',
	alphabetic_lower_b = 'b',
	alphabetic_lower_c = 'c',
	alphabetic_lower_d = 'd',
	alphabetic_lower_e = 'e',
	alphabetic_lower_f = 'f',
	alphabetic_lower_g = 'g',
	alphabetic_lower_h = 'h',
	alphabetic_lower_i = 'i',
	alphabetic_lower_j = 'j',
	alphabetic_lower_k = 'k',
	alphabetic_lower_l = 'l',
	alphabetic_lower_m = 'm',
	alphabetic_lower_n = 'n',
	alphabetic_lower_o = 'o',
	alphabetic_lower_p = 'p',
	alphabetic_lower_q = 'q',
	alphabetic_lower_r = 'r',
	alphabetic_lower_s = 's',
	alphabetic_lower_t = 't',
	alphabetic_lower_u = 'u',
	alphabetic_lower_v = 'v',
	alphabetic_lower_w = 'w',
	alphabetic_lower_x = 'x',
	alphabetic_lower_y = 'y',
	alphabetic_lower_z = 'z',
	punctuation_left_curly_bracket = '{',
	punctuation_vertical_bar = '|',
	punctuation_right_curly_bracket = '}',
	punctuation_tilde = '~',
	control_delete = '\127'
};

#endif //!TOOL_CHARACTER_VALUES_H_